### PR TITLE
SO Stream module

### PR DESCRIPTION
**Pull request by jlashner**
Adds a module to connect a smurf-data stream to the lyrebird server. Includes support for different focal plane configurations, including a grid layout and a wafer layout (determined by a hardware.toml file).

I have found that it is much easier to run in the mode where the connector is the frame server, and lyrebird connects to the port rather than the other way around. Meaning the connector uses a G3NetworkSender publishing to host "*" while lyrebird opens the reader with the host "localhost". This way the lyrebird visualizer can connect and disconnect easily without the connector having to reset. 

Also, if the sdstream config frame is a `Wiring` or `Observation` frame, it will always be the first frame received by the visualizer regardless of when the connector started (finally this feature comes in handy).

I realize that this might not be the right location for this module so we might want to move it to another directory or repository.

### CODE REVIEW

**Review by mhasself — CHANGES_REQUESTED** [review]
Awesome.  I think as long as we keep lyrebird-vis and the SDStreamer schema "generic", it's ok to collect a few SO-specific scripts in here (where here is the generic_datastream branch).

Please restore the functionality of sd_demo.py, assuming that the use of Wiring has broken it.  If you also want to change it to client/server instead of server/client I think that doesn't bother me.

I'm not saying you have to comment every class and function, but I think you should provide a little more supporting context at the top of so_stream.py; including:
- this is for SO Smurf readout
- the smurf-streamer has to be running, at the src address
- lyrebird should be launched with the config file generated by sd_demo.py (assuming that's still true)
- how do you generate a toml file for the wafer view?

**Comment by jlashner** [comment]
Alright, thanks for the feedback! I added a docstring for the so_stream module, and restored functionality to the sd_demo.py script. 

Switching the config frame to Wiring type had some unexpected consequences, since the Wiring frame wasn't pushed through the G3Pipeline until a Scan frame was also sent. I was able to fix this by making a few changes to sd_demo like separating the generator and pacer counters, and making sure the sdstreamer code threw away all G3Pipeline info frames. I tested the module with these changes though and made sure it worked.

I also added a script `extract_wafer_dets.py` which takes a `hardware.toml` file generated by the `so_hardware_sim` sotodlib tool and outputs a toml file with just the detectors for a single wafer (this is necessary since loading the whole hardware.toml file takes a while, ~30 sec).

**Review by mhasself — APPROVED** [review]
Thanks.

For in-lab usage I suspect people might want a view where things are organized by subband, even if lots of channels are turned off.  Not clear to me if your current code only really works if 4096 channels are streamed.

I'm thinking you could divide the output space into a 2x4 grid, with each cell representing a subband, then drop little squares down for each detector, in the right cell of the grid, for each active detector in the band.  It is helpful if they are frequency-ordered.

This is not a change request though, I'm just looking to the future.

**Comment by jlashner** [comment]
Sweet, yeah that's not a bad idea. I think the way this is programmed it's pretty straight forward to add alternative focalplane configurations, so I can see someone adding that in the future.

The grid-mode actually adds in gaps between bands, so it's obvious where the band divisions are. The x- and y-dimensions of the grid are settable via command line args, so it's definitely possible to limit the view to just a single band, or a single AMCc with what's already written.

**Pull request merged**
